INSERT INTO ALONE_APP_VERSION VALUES ('v0.7.0',  now(), 'USERNAME');
alter table WTS_PAPER drop column MODELTYPE;

DELETE FROM WTS_SUBJECT_USEROWN WHERE CARDID is not null;
DELETE FROM WTS_PAPER_USEROWN ;

alter table WTS_ROOM_PAPER add NAME varchar(512);

