ALTER TABLE WTS_CARD ADD INDEX USER_PAPER_CARD (PAPERID,USERID,ROOMID);
ALTER TABLE wts_card_answer ADD INDEX USER_ANSWER (CARDID,VERSIONID,ANSWERID);
ALTER TABLE wts_card_answer ADD INDEX USER_SUBVERSION (CARDID,VERSIONID);