<%@ page language="java" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib uri="/view/conf/farmtag.tld" prefix="PF"%>
<div id="chooseCssIconsDivId" style="">
</div>
<script type="text/javascript">
	$(function() {
		appendIcon("icon-blank");
		appendIcon("icon-add");
		appendIcon("icon-edit");
		appendIcon("icon-remove");
		appendIcon("icon-save");
		appendIcon("icon-cut");
		appendIcon("icon-ok");
		appendIcon("icon-no");
		appendIcon("icon-cancel");
		appendIcon("icon-reload");
		appendIcon("icon-search");
		appendIcon("icon-print");
		appendIcon("icon-help");
		appendIcon("icon-undo");
		appendIcon("icon-redo");
		appendIcon("icon-back");
		appendIcon("icon-sum");
		appendIcon("icon-tip");
		appendIcon("icon-mini-add");
		appendIcon("icon-mini-edit");
		appendIcon("icon-mini-refresh");
		appendIcon("icon-address-book-open");
		appendIcon("icon-address-book");
		appendIcon("icon-address");
		appendIcon("icon-administrative-docs");
		appendIcon("icon-advertising");
		appendIcon("icon-application_osx_terminal");
		appendIcon("icon-archives");
		appendIcon("icon-arrow_refresh");
		appendIcon("icon-arrow_rotate_clockwise");
		appendIcon("icon-attibutes");
		appendIcon("icon-bank");
		appendIcon("icon-basket");
		appendIcon("icon-bell");
		appendIcon("icon-bestseller");
		appendIcon("icon-billing");
		appendIcon("icon-blog--arrow");
		appendIcon("icon-blog");
		appendIcon("icon-blogs");
		appendIcon("icon-bookmark");
		appendIcon("icon-books-brown");
		appendIcon("icon-brainstorming");
		appendIcon("icon-business-contact");
		appendIcon("icon-busy");
		appendIcon("icon-calendar");
		appendIcon("icon-cash_register_2");
		appendIcon("icon-category");
		appendIcon("icon-cd_burn");
		appendIcon("icon-check");
		appendIcon("icon-client_account_template");
		appendIcon("icon-collaboration");
		appendIcon("icon-comment");
		appendIcon("icon-communication");
		appendIcon("icon-computer");
		appendIcon("icon-config");
		appendIcon("icon-consulting");
		appendIcon("icon-contact");
		appendIcon("icon-cost");
		appendIcon("icon-credit-card");
		appendIcon("icon-credit");
		appendIcon("icon-current-work");
		appendIcon("icon-customers");
		appendIcon("icon-cv");
		appendIcon("icon-database");
		appendIcon("icon-database_gear");
		appendIcon("icon-date");
		appendIcon("icon-date_magnify");
		appendIcon("icon-delicious");
		appendIcon("icon-document-library");
		appendIcon("icon-documents_email");
		appendIcon("icon-donate");
		appendIcon("icon-drawings");
		appendIcon("icon-edit");
		appendIcon("icon-email");
		appendIcon("icon-error");
		appendIcon("icon-error_delete");
		appendIcon("icon-exclamation-button");
		appendIcon("icon-exclamation-diamond-frame");
		appendIcon("icon-exclamation-octagon-frame");
		appendIcon("icon-exclamation-red-frame");
		appendIcon("icon-exclamation-shield-frame");
		appendIcon("icon-exclamation-white");
		appendIcon("icon-exclamation");
		appendIcon("icon-eye");
		appendIcon("icon-featured");
		appendIcon("icon-feed");
		appendIcon("icon-finished-work");
		appendIcon("icon-fire--exclamation");
		appendIcon("icon-fire-big");
		appendIcon("icon-flag");
		appendIcon("icon-folder");
		appendIcon("icon-free-for-job");
		appendIcon("icon-freelance");
		appendIcon("icon-full-time");
		appendIcon("icon-future-projects");
		appendIcon("icon-graphic-design");
		appendIcon("icon-group_green_edit");
		appendIcon("icon-group_green_new");
		appendIcon("icon-heart");
		appendIcon("icon-hire-me");
		appendIcon("icon-home");
		appendIcon("icon-illustration");
		appendIcon("icon-invoice");
		appendIcon("icon-issue");
		appendIcon("icon-library");
		appendIcon("icon-lightbulb");
		appendIcon("icon-limited-edition");
		appendIcon("icon-link");
		appendIcon("icon-lock");
		appendIcon("icon-login");
		appendIcon("icon-logout");
		appendIcon("icon-map");
		appendIcon("icon-map2");
		appendIcon("icon-milestone");
		appendIcon("icon-move_to_folder");
		appendIcon("icon-my-account");
		appendIcon("icon-networking");
		appendIcon("icon-old-versions");
		appendIcon("icon-order-1");
		appendIcon("icon-order");
		appendIcon("icon-page_paintbrush");
		appendIcon("icon-page_paste");
		appendIcon("icon-payment-card");
		appendIcon("icon-paypal");
		appendIcon("icon-pen");
		appendIcon("icon-pencil");
		appendIcon("icon-phone");
		appendIcon("icon-photography");
		appendIcon("icon-plus");
		appendIcon("icon-premium");
		appendIcon("icon-print");
		appendIcon("icon-process");
		appendIcon("icon-product-1");
		appendIcon("icon-product-design");
		appendIcon("icon-product");
		appendIcon("icon-project");
		appendIcon("icon-publish");
		appendIcon("icon-refresh");
		appendIcon("icon-report");
		appendIcon("icon-report_edit");
		appendIcon("icon-search");
		appendIcon("icon-settings");
		appendIcon("icon-shipping");
		appendIcon("icon-showreel");
		appendIcon("icon-sign-in");
		appendIcon("icon-sign-out");
		appendIcon("icon-sign-up");
		appendIcon("icon-sitemap-application");
		appendIcon("icon-sitemap");
		appendIcon("icon-sound");
		appendIcon("icon-sound_low");
		appendIcon("icon-special-offer");
		appendIcon("icon-sprocket_dark");
		appendIcon("icon-star");
		appendIcon("icon-statistics");
		appendIcon("icon-suppliers");
		appendIcon("icon-tag");
		appendIcon("icon-ticket");
		appendIcon("icon-twitter");
		appendIcon("icon-upcoming-work");
		appendIcon("icon-user");
		appendIcon("icon-user_gray");
		appendIcon("icon-user_green");
		appendIcon("icon-user_medical");
		appendIcon("icon-user_nude");
		appendIcon("icon-user_orange");
		appendIcon("icon-user_police_england");
		appendIcon("icon-user_soldier");
		appendIcon("icon-world");
		appendIcon("icon-zoom");
		$('div','#chooseCssIconsDivId').each(function(i,o){
				 $(o).bind('click',function(){
				 	$('#chooseImg').linkbutton({   
					    iconCls: $(this).attr('class') 
					});  
				 	$('#iconTextSpanId').text($(this).attr('class'));
				 	$('#entity_img_id').val($(this).attr('class'));
				 	$('#windowChooseImg').window('close'); 
				 });
		});
	})
	function appendIcon(classStr) {
		$('#chooseCssIconsDivId')
				.append(
						'<div class="' + classStr + '" style="width: 32px; height: 32px; border: 1px solid #666666;cursor: pointer; margin: 4px; float: left;"></div>');
		
	}
	//-->
</script>